microservice-chart:
  namespace: "apiconfig"

  image:
    repository: ghcr.io/pagopa/ubuntu-vm
    tag: 1.0.0
    pullPolicy: Always

  deployment:
    create: true
    replicas: 1

  tmpVolumeMount:
    create: true
    mounts:
      - name: tmp
        mountPath: /tmp
      - name: logs
        mountPath: /app/logs

  livenessProbe:
    httpGet:
      path: /status/live
      port: 8080
    initialDelaySeconds: 30
    failureThreshold: 6
    periodSeconds: 10

  readinessProbe:
    httpGet:
      path: /status/ready
      port: 8080
    initialDelaySeconds: 30
    failureThreshold: 6
    periodSeconds: 10

  service:
    create: true
    type: ClusterIP
    ports:
      - 8080

  ingress:
    create: true
    host: "weudev.apiconfig.internal.dev.platform.pagopa.it"
    path: /diego/java-helm-complete-test(/|$)(.*)
    rewriteTarget: /$2
    servicePort: 8080

  serviceAccount:
    create: false
    annotations: {}
    name: ""

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "256Mi"
      cpu: "40m"
    limits:
      memory: "256Mi"
      cpu: "150m"

  autoscaling:
    enable: true
    minReplica: 1
    maxReplica: 3
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization
          value: "60"


  envConfig:
    SPRING_DATASOURCE_USERNAME: 'NODO4_CFG'
  envSecret:
    SPRING_DATASOURCE_PASSWORD: 'oracle-db-cfg-password'
  keyvault:
    name: "pagopa-d-apiconfig-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"


